---
title: "TP3_Monte_Carlo"
author: "Zeyu CHEN"
date: "2019/2/27"
output: pdf_document
---

###1.1 On supose que P(Y=-1)=x et P(Y=1)=y
on a : 
 -x + y = 1/6
  x + y = 1/6
Facilement on a x = 0 y = 1/6

###1.2
$$Var(X)=E(X^2)-E(X)^2$$
Var(Y)= 1*1/6 - 1/36 = 5/36

Parce que la distribution de Y est plus uniforme
###1.3
```{r, include = TRUE}
echantillion_X_Y <- function(p1,p2,N)
{
  X <- rep(0,N)
  for(i in 1:N)
  {
  u <- runif(1)
  if(u <= p1)
    X[i] = -1
  else if(u<=p2+p1)
    X[i] = 0
  else 
    X[i]= 1
  }
  return(X)
}

trace_moyenne_empirique_X_Y<- function(p1,p2,N)
{
  X <- rep(0,N)
  for(i in 1:N)
  {
    X[i] <-mean(echantillion_X_Y(p1,p2,i))
  }
  return (X)
}

X_N <- trace_moyenne_empirique_X_Y(1/3,1/6,1000)
plot(X_N,ylim=c(-1,1))
Y_N <- trace_moyenne_empirique_X_Y(0,5/6,1000)
plot(Y_N,ylim=c(-1,1))

```

###
$$IC = [\bar{X}_N -  C_{\alpha}\frac{S_N}{\sqrt{N}},\bar{X}_N +  C_{\alpha}\frac{S_N}{\sqrt{N}} ]$$ 
On veut que ça soit IC de 95% , ou $C_{\alpha}=1.96$

```{r, include = TRUE}
  N <- 1000
  X_ <- rep(0,N)
  Inf_Ic <- rep(0,N)
  Sup_Ic <- rep(0,N)
  for(i in 2:N)
  {
    X <- echantillion_X_Y(1/3,1/6,i)
    X_[i] <- mean(X)
    S_N <- sqrt(sum((X-X_[i])^2)/(i-1))
    Inf_Ic[i] <- X_[i] - 1.96*S_N/sqrt(i)
    Sup_Ic[i] <- X_[i] + 1.96*S_N/sqrt(i)
  }
plot(X_,type="l")
lines(Sup_Ic,col="blue")
lines(Inf_Ic,col="red")
```


$$|\bar{X}_N -  C_{\alpha}\frac{S_N}{\sqrt{N}}|<0.01$$
###1.5
```{r, include = TRUE}

Approximatif_N_X<- function(error=1)
{
  N_0=10
  i=10
  while(error>0.05)
  {
    X = echantillion_X_Y(1/3,1/6,i)
    X_=mean(X)
    S_N = sqrt(sum((X-X_)^2)/(i-1))
    error  = 1.96*S_N/sqrt(i)
    i=i+1
    N_0=N_0+1
  }
  return (N_0)
}


Approximatif_N_Y<- function(error=1)
{
  N_0<-10
  i<-10
  while(error>0.05)
  {
    Y <- echantillion_X_Y(0,5/6,i)
    Y_<- mean(Y)
    S_N <-sqrt(sum((Y-Y_)^2)/(i-1))
    error  <- 1.96*S_N/sqrt(i)
    i<-i+1
    N_0=N_0+1
  }
  return (N_0)
}

Approximatif_N_X(1)
Approximatif_N_Y(1)

```

###2.1
```{r, include = TRUE}
echantillon_g_X <- function(n)
{
ret <- numeric(n)
for(i in 1:n)
{
x <- rnorm(1)
ret[i] <- ifelse(x >= 3.5, x, 0)
}
return(ret)
}
#On génère alors un échantillon de taille n = 10000 avec la fonction précédente :
echantillon_g_X_10000 <- echantillon_g_X(1000)
#On estime alors par la méthode de Monte-Carlo E(g(X)) :
print(mean(echantillon_g_X_10000))
```


###2.2
```{r, include = TRUE}
N <- 1000
Inf_Ic <- rep(0,N)
Sup_Ic <- rep(0,N)
X_N <- rep(0,N)
for(i in 2:N)
  {
    X <- rnorm(i)
    X_N[i] <- mean(X)
    S_N <- sqrt(sum((X-X_N[i])^2)/(i-1))
    Inf_Ic[i] <- X_N[i] - 1.96*S_N/sqrt(i)
    Sup_Ic[i] <- X_N[i] + 1.96*S_N/sqrt(i)
  }
plot(X_N)
lines(Inf_Ic,col="red")
lines(Sup_Ic,col="blue")
```
###2.3(a)
$$\mathbb{E}(g(X))=\int_{\mathbb{R}}g(x)\frac{1}{\sqrt{2\pi}}e^{\frac{-x^{2}}{2}}dx=\int_{\mathbb{R}}g(x)\frac{\frac{1}{\sqrt{2\pi}}e^{\frac{-x^{2}}{2}}}{\frac{1}{\sqrt{2\pi}}e^{\frac{-(x-\mu)^{2}}{2}}}\frac{1}{\sqrt{2\pi}}e^{\frac{-(x-\mu)^{2}}{2}}dx=\mathbb{E}(\psi(Z^{\mu}))$$

$$\psi(x)=g(x)e^{\frac{\mu(\mu-2x)}{2}}$$

###2.3(b)


```{r, include = TRUE}
echantillon_psi_Z <-function(N,mu)
{
E_gX <- rep(0,N)
for(i in 1:N)
{
  X <- rnorm(1)
  Z <- X+2.5
  if(Z >= 3.5)
  {
    E_gX[i] = Z*exp((mu^2-2*Z*mu)/2)
  }
  else
  {
    E_gX[i]=0
  }
}
  return(E_gX)
}
mean(echantillon_psi_Z(10000,0.22))
```

###2.3(c)
```{r, include = TRUE}
N <- 200
Inf_Ic <- rep(0,N)
Sup_Ic <- rep(0,N)
X_N <- rep(0,N)
for(i in 2:N)
  {
    X <- echantillon_g_X(i)
    X_N[i] <- mean(X)
    S_N <- sqrt(sum((X-X_N[i])^2)/(i-1))
    Inf_Ic[i] <- X_N[i] - 1.96*S_N/sqrt(i)
    Sup_Ic[i] <- X_N[i] + 1.96*S_N/sqrt(i)
  }
plot(X_N,ylim = c(0,0.1),col=26)
lines(Inf_Ic,col="red")
lines(Sup_Ic,col="blue")


N <- 200
Inf_Ic <- rep(0,N)
Sup_Ic <- rep(0,N)
X_N <- rep(0,N)
for(i in 2:N)
{
    X <- echantillon_psi_Z(i,2.5)
    X_N[i] <- mean(X)
    S_N <- sqrt(sum((X-X_N[i])^2)/(i-1))
    Inf_Ic[i] <- X_N[i] - 1.96*S_N/sqrt(i)
    Sup_Ic[i] <- X_N[i] + 1.96*S_N/sqrt(i)
}
par(new=TRUE)
plot(X_N,ylim = c(0,0.1),col="255")
lines(Inf_Ic,col="red")
lines(Sup_Ic,col="blue")
legend(x = "topright", legend = c("Moyennes via X", "Moyennes via Z"), pch = c(1, 1),col = c(26,255))
```

###2.3(e)
```{r, include = TRUE}

N <- 1000
Inf_Ic <- rep(0,N)
Sup_Ic <- rep(0,N)
X_N <- rep(0,N)
for(i in 2:N)
  {
    X <- echantillon_psi_Z(i,2.5)
    X_N[i] <- mean(X)
    S_N <- sqrt(sum((X-X_N[i])^2)/(i-1))
    Inf_Ic[i] <- X_N[i] - 1.96*S_N/sqrt(i)
    Sup_Ic[i] <- X_N[i] + 1.96*S_N/sqrt(i)
}

plot(X_N,col="555",ylim = c(0,0.003))
lines(Inf_Ic,col="red")
lines(Sup_Ic,col="blue")

```

###2.4
```{r, include = TRUE}
mu0 = 1
gradient =2
alpha=0.001
while(abs(gradient)>exp(-30))
{
  sig <- rnorm(1)
  if(mu0 + sig>= 3.5)
  {
    gradient <- (2*(mu0+sig)+((mu0+sig)^2)*(-2*mu0-2*sig))*exp((-mu0^2)-2*mu0*sig)
    mu0 <- mu0 - alpha*gradient
  }
  else
  {
    mu0 <- mu0
  }
}
mu0

```

```{r, include = TRUE}
N <- 2000
Inf_Ic <- rep(0,N)
Sup_Ic <- rep(0,N)
X_N <- rep(0,N)
for(i in 2:N)
  {
    X <- echantillon_psi_Z(i,3)
    X_N[i] <- mean(X)
    S_N <- sqrt(sum((X-X_N[i])^2)/(i-1))
    Inf_Ic[i] <- X_N[i] - 1.96*S_N/sqrt(i)
    Sup_Ic[i] <- X_N[i] + 1.96*S_N/sqrt(i)
}

plot(X_N,col="255")
lines(Inf_Ic,col="red")
lines(Sup_Ic,col="blue")
```

```{r, include = TRUE}
Approximatif_psi_Z<- function()
{
  N_0<-0
  for(i in 2:N)
  {
    X <- echantillon_psi_Z(i,2.5)
    X_N[i] <- mean(X)
    S_N <- sqrt(sum((X-X_N[i])^2)/(i-1))
    error  <- 1.96*S_N/sqrt(i)
    if(error<0.01)
    {
      N_0<-i;
      break;
     }
  }
  return (N_0)
}
Approximatif_psi_Z()
```


