---
title: "KernelPCA and Spectral Clustering"
author: "Eric Wang"
date: "3 décembre 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(kernlab)
```

```{r}
data(spam)
set.seed(0)
selection<-sample(1:nrow(spam),400,replace=FALSE)
spam.select<-spam[selection,]
```

```{r}
# spam.pca <- PCA(spam,quali.sup=58)
# plot(spam.pca,choix="ind")

train <- sample(1:dim(spam)[1],400)
kpc <- kpca(~.,data=spam[train,-58],kernel='rbfdot',kpar=list(sigma=0.001),features=2)
kpcv <- pcv(kpc)
plot(rotated(kpc),col=as.integer(spam[train,58]),xlab="1st Principal Comp.",ylab="2nd Principal Comp.")

kpc<-kpca(~.,data=spam[train])
```

```{r Spectral clustering}
library(mlbench)
set.seed(111)
obj<-mlbench.spirals(100,1,0.025)
my.data<-data.frame(4*obj$x)
names(my.data)<-c("X1","X2")

par(mfrow=c(1,2))
plot(my.data,col=c('orange','blue')[obj$classes],main="original")
my.data<-as.matrix(my.data)

plot(my.data,col=c('orange','blue')[kmeans(my.data,2)$cluster],main="kmeans")
```

Avec gaussin kernel calculons K the matrix of similarities
$$
K(x_{i},x_{j}) = exp( \dfrac{ -||x_{i}-x_{j}||^{2}}{\sigma^{2}})
$$

```{r }


sigma2 <- 1

K <- exp(-as.matrix(dist(my.data))^2 / sigma2 )


sum(K>0.1)
sum(K>0.2)

image(K)
```
```{r avoir A}

A <- K > 0.5
diag(A)<-0

D <- diag(colSums(A))

L<- D- A
eigen(L)$values # les 2 dernieres valent '0' --> 2 composantes connexes

eigen(L)$vectors[,98]

table(eigen(L)$vectors[,98]>0,obj$classes) # ca marche mal trop d'erreur

table(kmeans(eigen(L)$vectors[,97:100],2)$cluster,obj$classes)


color.kmeans <- kmeans(eigen(L)$vectors[,97:100],2,nstart=30)$cluster

par(mfrow=c(1,3))
plot(my.data,col=c('orange','blue')[obj$classes],main="original")
plot(my.data,col=c('orange','blue')[kmeans(my.data,2)$cluster],main="kmeans")
plot(my.data,col=c('orange','blue')[color.kmeans],main="spectral kmeans")
```
chercher les voisins ets meilleur que threshold
