---
title: "TP5"
author: "FARRUGIA"
date: "26/11/2018"
output: html_document
---

```{r}
library(kernlab)
data(spam)
library(FactoMineR)
X <- data.frame(spam)
res <- PCA(X, quali.sup = 58)
plot.PCA(res, habillage=58, choix="ind")
```

```{r}
#set.seed(0)
selection <- sample(1:nrow(spam), 400, replace=F)
spam.select <- spam[selection,]
library(kernlab)
kpc <- kpca(~.,data=spam.select[,-58],kernel="rbfdot", kpar=list(sigma=0.001), features=2)
kpcv <- pcv(kpc)
plot(rotated(kpc), col=as.integer(spam.select[,58]), xlab="1st Principal Comp.", ylab="2nd Principal Comp.")
```


Exercice 2

```{r}
library(mlbench)
set.seed(111)
obj <- mlbench.spirals(100,1,0.025)
mydata <- data.frame(4*obj$x)
names(mydata) <- c("X1", "X2")
par(mfrow=c(1,2))
plot(mydata, col=c("blue", "red")[obj$classes],pch=19, main="differentes classes avec obj$classes")

plot(mydata, col=c("blue","red")[kmeans(mydata,2)$cluster], pch=19, main="differente classe avec les kmeans")
```


Si sigma^2 est grand K =matrix(1,n,n)
Si sigma^2 est petit K=Identite
```{r}
mydata <- as.matrix(mydata)
sigma2 <- 1
K <- exp(-as.matrix(dist(mydata))^2/sigma2)

```


```{r}
A <- K > 0.5
diag(A) <- 0
D<-diag(colSums(A))
L <- D-A
color.kmeans <- kmeans(eigen(L)$vectors[,97:100],2,nstart=30)$cluster
par(mfrow=c(1,3))
plot(mydata, col=c('orange','blue')[obj$classes],main="Original Classes", pch=19)
plot(mydata, col=c("orange","blue")[kmeans(mydata,2)$cluster], main="Kmeans",pch=19)
plot(mydata,col=c("orange", "blue")[color.kmeans],main="Spectral Kmeans",pch=19)

```


```{r}

spe <- specc(as.matrix(K),centers=2)
plot(mydata,col=spe, pch=19)

```